"""
Cars REST API routes (Flask-Smorest).

Provides:
- GET /api/cars: list cars with search/filter/sort/pagination
- GET /api/cars/<id>: get a single car by id

Uses:
- app.schemas.car for Marshmallow request args + response schemas
- app.repositories.in_memory_car_repository for data access

OpenAPI/Swagger docs are automatically generated by Flask-Smorest and available under /docs.
"""

from __future__ import annotations

from typing import Any, Dict

from flask.views import MethodView
from flask_smorest import Blueprint, abort

from app.repositories.repository_factory import get_car_repository
from app.schemas.car import CarListQueryArgsSchema, CarSchema, PaginatedCarsSchema

# Resolve the active repository once at import time (app startup).
_repo = get_car_repository()

blp = Blueprint(
    "Cars",
    __name__,
    url_prefix="/api/cars",
    description="Car listing and detail endpoints",
)


@blp.route("")
class CarsCollection(MethodView):
    """
    Collection resource for cars.

    Supports search/filter/sort/pagination via query parameters validated by Marshmallow.
    """

    @blp.arguments(CarListQueryArgsSchema, location="query")
    @blp.response(200, PaginatedCarsSchema)
    def get(self, args: Dict[str, Any]):
        """
        List cars (search/filter/sort/pagination).

        Query Parameters:
            q: Search text over make/model/name (case-insensitive; model is treated as "name")
            make: Make filter (case-insensitive exact match)
            model: Model filter (case-insensitive exact match)
            year_min/year_max: Inclusive year range filter
            price_min/price_max: Inclusive price range filter
            sort: Sort expression like '-price', 'price', 'year' (default: '-year')
            page: 1-based page index (default: 1)
            page_size: Page size (default: 12, max: 50)

        Returns:
            Envelope:
              { items: Car[], total: number, page: number, page_size: number }
        """
        return _repo.list_cars(**args)


@blp.route("/<string:car_id>")
class CarItem(MethodView):
    """Item resource for a single car."""

    @blp.response(200, CarSchema)
    def get(self, car_id: str):
        """
        Get a single car by id.

        Args:
            car_id: Car identifier string (uuid-like).

        Returns:
            The car object.

        Raises:
            404: If the car does not exist.
        """
        car = _repo.get_car_by_id(car_id)
        if car is None:
            abort(404, message="Car not found")
        return car
