"""
Cars REST API routes (Flask-Smorest).

Provides:
- GET /api/cars: list cars with search/filter/sort/pagination
- GET /api/cars/<id>: get a single car by id

Uses:
- app.schemas.car for Marshmallow request args + response schemas
- app.repositories.in_memory_car_repository for data access

OpenAPI/Swagger docs are automatically generated by Flask-Smorest and available under /docs.
"""

from __future__ import annotations

from typing import Any, Dict

from flask.views import MethodView
from flask_smorest import Blueprint, abort

from app.repositories import in_memory_car_repository
from app.schemas.car import CarListQueryArgsSchema, CarSchema, PaginatedCarsSchema

blp = Blueprint(
    "Cars",
    __name__,
    url_prefix="/api/cars",
    description="Car listing and detail endpoints",
)


@blp.route("")
class CarsCollection(MethodView):
    """
    Collection resource for cars.

    Supports search/filter/sort/pagination via query parameters validated by Marshmallow.
    """

    @blp.arguments(CarListQueryArgsSchema, location="query")
    @blp.response(200, PaginatedCarsSchema)
    def get(self, args: Dict[str, Any]):
        """
        List cars (search/filter/sort/pagination).

        Query Parameters:
            q: Text search across make/model (case-insensitive)
            year_min/year_max: Inclusive year range filter
            price_min/price_max: Inclusive price range filter
            sort_by: year|price|mileage|make|model
            sort_dir: asc|desc
            page: 1-based page index
            page_size: page size (1..100)

        Returns:
            A paginated envelope with `items` plus pagination metadata.
        """
        # Repository already returns an envelope matching PaginatedCarsSchema.
        return in_memory_car_repository.list_cars(**args)


@blp.route("/<string:car_id>")
class CarItem(MethodView):
    """Item resource for a single car."""

    @blp.response(200, CarSchema)
    def get(self, car_id: str):
        """
        Get a single car by id.

        Args:
            car_id: Car identifier string (uuid-like).

        Returns:
            The car object.

        Raises:
            404: If the car does not exist.
        """
        car = in_memory_car_repository.get_car_by_id(car_id)
        if car is None:
            abort(404, message="Car not found")
        return car
